# GitHub Pages Jekyll config
# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
# https://github.com/daviddarnes/alembic
theme: alembic-jekyll-theme
plugins:
  - jekyll-seo-tag
  - jekyll-commonmark
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout

# https://github.com/daviddarnes/alembic/blob/main/_config.yml
twitter:
  username: noraj_rawsec
author: noraj
social: # jekyll-seo-tag > social overrides
  name: Alexandre ZANNI # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://x.com/noraj_rawsec
    - https://github.com/noraj
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
commonmark:
  # options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "php-serialized-formatter" # Site name or title, also used in jekyll-seo-tag
logo: '/media/psf_logo.png' # Site logo, also used in jekyll-seo-tag
description: 'Tool to leak time on a remote machine by using ICMP timestamp requests (13) and replies (14).'
url: https://noraj.github.io/
baseurl: "/php-serialized-formatter/"
source: docs/
destination: output/
include:
  - README.md
repo: https://github.com/noraj/php-serialized-formatter
navigation_header:
- title: Home
  url: /
- title: Install
  url: /installation.html
- title: Use
  url: /usage.html
- title: Library
  url: /yard/
- title: Changes
  url: /CHANGELOG.html
- title: About
  url: /about.html
navigation_footer:
- title: Created by noraj
  url: https://pwn.by/noraj
social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  X: https://x.com/noraj_rawsec
  GitHub: https://github.com/noraj
readme_index:
  remove_originals: true
  with_frontmatter: false
optional_front_matter:
  remove_originals: true
